---
- name: Creates directory for haproxy config file
  file:
    path: /opt/haproxy
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Copy template haproxy.cfg config file
  template:
    src: haproxy.cfg.j2
    dest: /opt/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0755
    backup: yes
