---
- name: Deploy haproxy docker container
  docker_container:
        name: haproxy
        hostname: haproxy
        image: docker.io/hos7ein/haproxy
        networks_cli_compatible: yes
        networks:
          - name: app-net
        purge_networks: yes
        published_ports:
          - 5000:5000
        volumes:
          - /opt/haproxy:/etc/haproxy
        restart_policy: always
