- hosts: build_host
  remote_user: root
  gather_facts: False
  vars_files:
    - secrets.yml
  tasks:
    - name: create build directory
      file:
        path: /opt/demo-dockerfile
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Synchronization of src on the control machine to dest on the remote host
      synchronize:
        src: ../apps
        dest: /opt/demo-dockerfile

   - name: login to docker registry
     docker_login:
       username: "{{ docker_hub_username }}"
       password: "{{ docker_hub_password }}"
       email: "{{ docker_hub_email }}"
