- hosts: app_servers
  remote_user: root
  gather_facts: False
  vars:
    to_version: v1.0.0
  tasks:
    - debug:
       msg: Rollback to app {{ to_version }}

    - name: remove line to /opt/haproxy/haproxy.cfg file
      lineinfile:
        path: /opt/haproxy/haproxy.cfg
        state: absent
        regexp: '^server'

    - name: append line to /opt/haproxy/haproxy.cfg file
      lineinfile:
        path: /opt/haproxy/haproxy.cfg
        line: '{{item}}'
      with_items:
        - "server  app-{{ to_version }}   app-{{ to_version }}:3000 check"

    - name: reload haproxy config file
      shell: docker kill -s HUP haproxy-test
